# Generated by Django 5.1.1 on 2024-10-02 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subir_archivo', '0002_alter_subirarchivo_file'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='subirarchivo',
            table='subir_archivo',
        ),
    ]
