# Generated by Django 5.1.1 on 2024-10-03 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subir_archivo', '0003_alter_subirarchivo_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='subirarchivo',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
