# Generated by Django 5.0.6 on 2024-09-25 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido_1', models.CharField(max_length=50)),
                ('apellido_2', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('puesto', models.CharField(max_length=100)),
                ('fecha_contratación', models.DateField()),
                ('cumpleaños', models.DateField()),
                ('is_on_leave', models.BooleanField(default=False)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='empleados/')),
            ],
        ),
    ]
