# Generated by Django 5.0.6 on 2024-09-25 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='photo',
            new_name='foto',
        ),
    ]
