# Generated by Django 5.1.1 on 2024-10-04 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rolmodel_empleado_rol'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='fecha_contratación',
            new_name='fecha_contratacion',
        ),
    ]
