# Generated by Django 5.1.1 on 2024-10-04 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_fecha_contratación_empleado_fecha_contratacion'),
        ('sedes', '0007_sede_ciudad_sede_pais_alter_sede_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sedes.sede'),
        ),
    ]
