# Generated by Django 5.1.1 on 2024-10-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subir_archivo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subirarchivo',
            name='file',
            field=models.FileField(upload_to='uploaded_files/'),
        ),
    ]
