# Generated by Django 5.1.1 on 2024-10-03 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subir_archivo', '0004_subirarchivo_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subirarchivo',
            name='descripcion',
        ),
        migrations.AlterModelTable(
            name='subirarchivo',
            table=None,
        ),
    ]
