# Generated by Django 5.1.1 on 2024-10-03 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_photo_empleado_foto'),
        ('sedes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservasala',
            name='empleados',
            field=models.ManyToManyField(related_name='reuniones', to='core.empleado'),
        ),
    ]
