# Generated by Django 5.1.1 on 2024-10-03 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_photo_empleado_foto'),
        ('sedes', '0002_reservasala_empleados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservasala',
            name='empleados',
            field=models.ManyToManyField(blank=True, related_name='reservas', to='core.empleado'),
        ),
        migrations.AlterField(
            model_name='reservasala',
            name='reservado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empleado'),
        ),
        migrations.AlterField(
            model_name='reservasala',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sedes.salareuniones'),
        ),
    ]
