# Generated by Django 5.1.1 on 2024-10-03 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_photo_empleado_foto'),
        ('sedes', '0003_alter_reservasala_empleados_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservasala',
            name='empleados',
            field=models.ManyToManyField(related_name='reuniones', to='core.empleado'),
        ),
        migrations.AlterField(
            model_name='reservasala',
            name='reservado_por',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='reservasala',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='sedes.salareuniones'),
        ),
    ]
