# Generated by Django 5.1.1 on 2024-10-03 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sedes', '0004_alter_reservasala_empleados_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservasala',
            name='empleados',
        ),
    ]
