# Generated by Django 5.1.1 on 2024-10-03 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_photo_empleado_foto'),
        ('sedes', '0005_remove_reservasala_empleados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sede',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='sede',
            name='pais',
        ),
        migrations.AddField(
            model_name='reservasala',
            name='empleados_asistentes',
            field=models.ManyToManyField(blank=True, related_name='reservas_asistentes', to='core.empleado'),
        ),
        migrations.AlterField(
            model_name='reservasala',
            name='reservado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empleado'),
        ),
        migrations.AlterField(
            model_name='salareuniones',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sede',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelTable(
            name='reservasala',
            table='reservas_sala',
        ),
        migrations.AlterModelTable(
            name='salareuniones',
            table='salas_reuniones',
        ),
        migrations.AlterModelTable(
            name='sede',
            table='sedes',
        ),
    ]
